@ECHO OFF
SET PROJECT_NAME=dotnet-api-goat
SET IASTAGENT_PATH=c:\iast\iast-dev\out\agent\Debug\dotnet

IF NOT DEFINED DevEnvDir (
    CALL "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Tools\VsDevCmd.bat"
)

SET COR_ENABLE_PROFILING=1
SET COR_PROFILER={90747D54-A553-4353-8E39-CA9ADE930151}
SET COR_PROFILER_PATH=%IASTAGENT_PATH%\agent_dotnet_win32.dll

SET IASTAGENT_LOGGING_STDERR_LEVEL=info
SET IASTAGENT_LOGGING_FILE_ENABLED=true
SET IASTAGENT_LOGGING_FILE_LEVEL=info
SET IASTAGENT_LOGGING_FILE_PATHNAME=.\%PROJECT_NAME%-%IASTAGENT_LOGGING_STDERR_LEVEL%.log

vstest.console.exe .\bin\Debug\%PROJECT_NAME%.Tests.dll